# Generated by Django 5.2.17 on 2026-08-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес')),
                ('avito_url', models.URLField(blank=True, max_length=500, verbose_name='объявление на Avito')),
                ('realtycalendar_id', models.CharField(blank=True, max_length=100, verbose_name='идентификатор в RealtyCalendar')),
                ('min_nights', models.PositiveSmallIntegerField(default=2, verbose_name='минимальный срок, ночей')),
                ('is_active', models.BooleanField(default=True, verbose_name='в работе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='заведена')),
            ],
            options={
                'verbose_name': 'квартира',
                'verbose_name_plural': 'квартиры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='ссылка на объявление')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='заголовок')),
                ('min_nights', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='минимальный срок, ночей')),
                ('is_active', models.BooleanField(default=True, verbose_name='в работе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='заведён')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='monitor.apartment', verbose_name='квартира')),
            ],
            options={
                'verbose_name': 'конкурент',
                'verbose_name_plural': 'конкуренты',
                'ordering': ['title', 'url'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_kind', models.CharField(choices=[('listing', 'витринная «от N ₽»'), ('dated', 'на конкретные даты')], max_length=16, verbose_name='вид цены')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='дата заезда')),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ночей')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена за ночь')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='сумма за период')),
                ('fees_included', models.BooleanField(blank=True, null=True, verbose_name='сервисный сбор включён')),
                ('collected_at', models.DateTimeField(db_index=True, verbose_name='собрано')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('realtycalendar', 'RealtyCalendar')], max_length=20, verbose_name='источник')),
                ('status', models.CharField(choices=[('ok', 'получено'), ('failed', 'сбой'), ('blocked', 'блокировка'), ('not_available', 'объявление недоступно'), ('captcha_overlay', 'проверка поверх страницы')], max_length=20, verbose_name='исход')),
                ('error_note', models.TextField(blank=True, verbose_name='причина')),
                ('raw_dump_path', models.CharField(blank=True, max_length=500, verbose_name='дамп страницы')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='monitor.apartment', verbose_name='квартира')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='monitor.competitor', verbose_name='конкурент')),
            ],
            options={
                'verbose_name': 'снимок цены',
                'verbose_name_plural': 'снимки цен',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('apartment', 'url'), name='competitor_unique_url_per_apartment'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['competitor', 'check_in', '-collected_at'], name='snapshot_competitor_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['apartment', 'check_in', '-collected_at'], name='snapshot_apartment_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('apartment__isnull', True), ('competitor__isnull', False)), models.Q(('apartment__isnull', False), ('competitor__isnull', True)), _connector='OR'), name='snapshot_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_kind', 'listing'), _negated=True), models.Q(('check_in__isnull', True), ('nights__isnull', True)), _connector='OR'), name='snapshot_listing_has_no_dates'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_kind', 'dated'), ('status', 'ok'), _negated=True), models.Q(('check_in__isnull', False), ('nights__isnull', False)), _connector='OR'), name='snapshot_dated_ok_has_dates'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ok'), _negated=True), ('price_per_night__isnull', False), _connector='OR'), name='snapshot_ok_has_price'),
        ),
    ]
