# Generated by Django 5.2.17 on 2026-08-26 14:37

import monitor.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['title'], 'verbose_name': 'квартиру', 'verbose_name_plural': 'квартиры'},
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'ordering': ['title', 'url'], 'verbose_name': 'конкурента', 'verbose_name_plural': 'конкуренты'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='avito_url',
            field=models.URLField(blank=True, max_length=500, validators=[monitor.validators.validate_avito_url], verbose_name='объявление на Avito'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='url',
            field=models.URLField(max_length=500, validators=[monitor.validators.validate_avito_url], verbose_name='ссылка на объявление'),
        ),
    ]
