# Generated by Django 5.2.17 on 2026-08-29 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_apartment_options_alter_competitor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='дата заезда')),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ночей')),
                ('state', models.CharField(choices=[('pending', 'ждёт'), ('running', 'выполняется'), ('done', 'выполнено'), ('failed', 'сбой'), ('deferred', 'отложено')], db_index=True, default='pending', max_length=16, verbose_name='состояние')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='попыток')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='заведено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='закончено')),
                ('deferred_until', models.DateTimeField(blank=True, null=True, verbose_name='отложено до')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_tasks', to='monitor.apartment', verbose_name='квартира')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_tasks', to='monitor.competitor', verbose_name='конкурент')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.pricesnapshot', verbose_name='записанный снимок')),
            ],
            options={
                'verbose_name': 'задание сбора',
                'verbose_name_plural': 'задания сбора',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='task_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('apartment__isnull', True), ('competitor__isnull', False)), models.Q(('apartment__isnull', False), ('competitor__isnull', True)), _connector='OR'), name='task_exactly_one_owner')],
            },
        ),
    ]
