# Generated by Django 5.2.17 on 2026-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_collecttask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricesnapshot',
            name='snapshot_competitor_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricesnapshot',
            name='snapshot_apartment_idx',
        ),
        migrations.AddField(
            model_name='collecttask',
            name='guests',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='гостей'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='guests',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='гостей'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['competitor', 'check_in', 'nights', 'guests', '-collected_at'], name='snapshot_competitor_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['apartment', 'check_in', 'nights', 'guests', '-collected_at'], name='snapshot_apartment_idx'),
        ),
    ]
