"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-h%n$o0n!&6cl-bfnd)jedqawb7d3!xbnu!p!lw@xd@6b3)t4pz',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# Показ идёт через временный туннель Cloudflare, и имя у туннеля каждый раз
# новое. Поэтому в списке стоит весь домен, а не конкретный адрес: иначе
# перезапуск туннеля посреди показа означал бы правку настроек.
ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.trycloudflare.com'
).split(',')

# Туннель отдаёт страницы по https с чужого имени, а Django сверяет заголовок
# Origin каждого POST со своим списком. Без этой строки не проходит даже вход:
# форма отправляется и возвращается отказом проверки CSRF.
# Список выводится из ALLOWED_HOSTS, чтобы имя туннеля не пришлось держать
# в двух местах и однажды поправить только в одном.
CSRF_TRUSTED_ORIGINS = [
    f'https://*{host}' if host.startswith('.') else f'https://{host}'
    for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Закрывает вход целиком, а не постранично: инструмент внутренний, и
    # страница, которую забыли закрыть декоратором, — это открытая страница.
    # Формы входа исключены из проверки самим Django, включая вход в админку.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# Квартиры в Москве, менеджер работает по московскому времени: даты горизонта
# и возраст снимков считаются в нём, иначе «сегодня» уезжает на сутки.
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Bootstrap называет этот класс danger, а Django — error.
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

# Менеджер вставляет ссылки на объявления руками; ссылка без схемы должна стать
# https, а не http. В Django 6 это поведение станет умолчанием.
FORMS_URLFIELD_ASSUME_HTTPS = True

# Горизонт дат: сколько ближайших дат заезда показывает страница сравнения.
# Настройка, а не константа: реальное число упрётся в лимиты частоты обращений
# и в количество конкурентов, а оно пока неизвестно. Нигде не хардкодится.
PRICE_HORIZON_DAYS = int(os.environ.get('PRICE_HORIZON_DAYS', '7'))

# Снимок старше этого срока показывается на странице с возрастом данных.
STALE_AFTER_HOURS = 12

# Пауза между обращениями к площадке. Медленнее, чем 3–6 секунд из CLAUDE.md:
# разведка фазы 0 упёрлась в отказ «слишком много запросов» примерно на 135-м
# обращении, и темп — единственный рычаг, который правилами разрешён.
COLLECT_PAUSE_SECONDS = (
    float(os.environ.get('COLLECT_PAUSE_MIN', '15')),
    float(os.environ.get('COLLECT_PAUSE_MAX', '30')),
)

# На сколько откладывается задание, когда площадка показала проверку.
# Проходит её человек, поэтому срок измеряется рабочим днём, а не минутами.
COLLECT_DEFER_HOURS = int(os.environ.get('COLLECT_DEFER_HOURS', '8'))

# Число гостей, при котором собираются цены. Одинаковое для всех объявлений:
# цена зависит от числа гостей, и снимки на двоих и на четверых несопоставимы —
# та же ошибка, что сравнение периодов разной длины.
COLLECT_GUESTS = int(os.environ.get('COLLECT_GUESTS', '2'))


# Вход. Ролей и прав в проекте нет: пользователей двое, и оба видят всё.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'apartment-list'
LOGOUT_REDIRECT_URL = 'login'

# Менеджер заходит три раза в день с одной и той же машины. Месяц с продлением
# при каждом обращении — чтобы вход не превратился в ежедневный обряд.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_SAVE_EVERY_REQUEST = True
